Game logic
thneves/Tic-Tac-Toe-Game pull request #5
Opened 2020-10-21 16:41 UTC by thneves

- Set up all game logics
- the game asks for the name of the players before it start
- implement winning and draw messages in the ened
- created option to play again

2020-10-21 17:53 UTC, kubilaycaglayan requested changes
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏👋
The gameplay is amazing, everything is working fine.
Let's cover a few details together to make your project better 😊⏬

## General Requirements

- [x] Let's delete the .gitkeep file, we don't need it anymore 😊

- [x] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

💡 Check the inline comments, please ⏬

- [x] The game is not working out of the box. Please fix it.
[HINT] check `require`
- [x] [OPTIONAL] Using `require_relative` for files in your directory instead of `require` is a ruby convention.

![image](https://user-images.githubusercontent.com/60448833/96755511-7bc1dc00-13db-11eb-877c-f2ada6879c01.png)

## [REQUIRED] Functional Programming

### All the code in the `main.rb` file 😱 (current situation)
- [x] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot] (should be)(https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

💡 Okay, you have two classes in the `lib/` directory but they are so thin. All the code is still running in the `main.rb` file.

I will share some tips with you, about how you can move methods to the lib. And how you can make your methods single responsible. Right now you don't have many functions. Everything is running with the interpreter flow.

### Beautify the main.rb
This is your main.rb. It consists of a few initial variables and a `main game loop`.
You can move items in the green box into another file.
And we have our main loop here. We will work on this while loop, more.
![image](https://user-images.githubusercontent.com/60448833/96756544-ddcf1100-13dc-11eb-86f0-e240110ec1ac.png)

### Make a brand new function from this validator and call it here, instead of putting the code block here.
After you do this, instead of this thick code block, you will only call the method you created and you will use the return value from that method to go on with the loop. You can add this new method to your `Game` class.
![image](https://user-images.githubusercontent.com/60448833/96756905-6483ee00-13dd-11eb-9e90-74abb2d4a3ee.png)

### Make a brand new function from this code block
You can return a string value at the end and make the printing process here in main.rb. But you can put this method in your `Game` class.
![image](https://user-images.githubusercontent.com/60448833/96757186-c5abc180-13dd-11eb-8378-5eb9a6e2e02a.png)

### Make a brand new function from this code block
Similar to the above. You can move this into the `Game` class.
![image](https://user-images.githubusercontent.com/60448833/96757358-fee43180-13dd-11eb-998d-2214b9c422a1.png)

### Make a brand new function from this code block
You can move this into the `Player` class. You can initialize an instance variable named `@current_player`. And make the switching with your instance method.
![image](https://user-images.githubusercontent.com/60448833/96757468-23400e00-13de-11eb-955e-8192eaa2a032.png)

... It goes on like this. There are two more blocks but I believe you get the idea.

😇 I know it won't be too easy to make these changes. Maybe you'll need to alter some of your main logic in your game. But please give attention to this. Because it is a really important practice for functional programming. And this is one of the hard requirements of the project. 

- [x] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [x] User attr_readers/attr_writers. Only use attr_accessors if you really need it and you must be aware that by using it you allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [x] DRY rule should be respected. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/dry.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### Finally, you can put that great big while loop into a function and call it to initialize the game.

## That's it, you can request another code review request after making the changes ♻️😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-21 17:53 UTC, kubilaycaglayan commented on lib/game.rb
> +  end
:bulb: No puts/print outside of the main.rb.

2020-10-22 01:06 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @thneves and @Jhdezj :lollipop: :balloon: 

### Thank you for doing the changes requested by the previous reviewer :medal_sports: :medal_sports: your game and code have improved a lot since the previous review, I personally like you request for the player's names and you restart the game whenever they want to play again I think this makes your game more human friendly and stands out from the rest :video_game: :star: let's work on the following changes :construction: :construction_worker: :construction_worker: 

#### Behaviour

- [ ] The game is letting players have empty names 
> let's validate that the players don't have the same name and also can't have empty names
![image](https://user-images.githubusercontent.com/52209067/96804940-a1e07f80-13cd-11eb-9af3-5205d6191d0e.png)

- [ ] The game is showing both winning and tie messages when the game is won with the last available position.

> The game should either have a winner or be a tie let's fix it
![image](https://user-images.githubusercontent.com/52209067/96805118-13b8c900-13ce-11eb-8fa1-6df217ea5462.png)

#### Implementation Details

- [ ] You should use attr_readers/attr_writers. Only use attr_accessors if you really need it and must be aware that by using it they allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

> It's not a good coding practice to use attr_accessors not only because your game could be a victim of cheating but also they take more space in memory 

#### General

- [x] Your linters seem to be turned off please submit for a code review when you have a green checkmark in your last commit.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-10-22 01:06 UTC, euqueme commented on lib/game.rb
> +  attr_accessor :spots, :winner, :draw, :board, :game_on, :first_run, :validator, :current_player
- [ ] these are the only attr_accessors you need please declare the others as attr_reader

` :current_player, :spots, :first_run, :validator, :game_on`

2020-10-22 01:06 UTC, euqueme commented on lib/player.rb
> +  attr_accessor :name, :mark_spots, :current_player
- [ ] The only attr_accessor for this class should be :current_player the others could be attr_readers and your game still works correctly

2020-10-22 14:13 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi Team :wave: 
Thanks for addressing the changes mentioned by previous reviewers!
I see no need for further review!

### Optional
- Consider Letting player know that they are Player 1 or Player 2 when they do not enter a name though! [OPTIONAL]


***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-10-22 14:37 UTC, merged